### ISSUE TITLE
display: block

### ISSUE THREAD

**Issue by kumavis** [flyswatter/Speakeasy-CSS#1]
input: "style display block"

PARSING display:block
bundle.js:129 Setting  to display:block

**Comment by danfinlay** [comment]
Yeah this is super weird.  Sometimes the voice parser formats its own output with semicolons and proper Css formatting!!
- Dan

**Comment by kumavis** [comment]
I thought that might be what was happening w/o looking at the code -- weird. css is seeping into vernacular?
